config/routes.rb
Rails.application.routes.draw do
  resources :actors

  root 'actors#index'

end

app/models/actor.rb
class Actor < ActiveRecord::Base
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController

  def index
    @glumci = Actor.all
  end

  def new
    @glumac = Actor.new
  end

  def create
    Actor.create(actor_parameters)
    flash[:notice] = "Actor has been added!"
    redirect_to root_path
  end

  def destroy
    delact = Actor.find(params[:id])
    delact.destroy
    flash[:notice] = "Actor has been deleted!"
    redirect_to root_path
  end

  private

  def actor_parameters
    params.require(:actor).permit(:firstname, :lastname)
    # :actor being controller/db:table name
    # :firstname, :lastname being column names in db:table
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/actors/index.html.erb
<div class="container">

<h1> Absolute beginner's tutorial to Rails and AJAX </h1>
<hr />
<p><img src="http://perfectial.com/wp-content/uploads/2015/02/ruby.png" style="height:96px; width:auto; float:left; padding-right: 10px;">Maybe it's just me, I'm too stupid to get it, but I really did not find an adequate tutorial which would give me a glimpse to how to do just basic AJAX on Rails. That is why I decided to write my own. Just by sticking to the basics, and the concept behind these two, I want to help other people introduce themselves to this handy techniques. I wil have a diagram drawn, and put all my code to GitHub, so other can benefit.</p>
<p>Writing notes to myself... first thing I notice is that we need to know jQuery, CoffeeScript, Rails partials</p>
<p> First of... we are going classical! AJAX will be an upgrade, by refactoring the existing application. That way is, I believe, easier to understand.</p>
<p> Application is as simple as registering the First and the Last Name of your favourite actors (be it male or female). We will set two columns in our 'actors' table > firstname, lastname (text). </p>
<p> <%= link_to 'Add new Actor or Actress', new_actor_path(), class: 'btn btn-warning' %> <p>
<hr />
<div id="actor-display" class="jumbotron">
<% @glumci.each do |actor|%>
<%= actor.firstname %> <%= actor.lastname %> (<%= link_to 'X', actor_path(actor), method: 'delete' %>),
<% end %>
</div>
<hr />
<% if flash[:notice] %>
    <div class="alert alert-info"><%= flash[:notice] %></div>
  <% end %>
<div id="devlog">
  <!-- <img src="http://edgibbs.com/images/sourcetree_icon.png" style="height:32px; width:auto; padding-right: 10px;"> -->
  <h2>Development log</h2>
  <p> #1. rails new russ-quick-ajax </p>
  <p> #2. rails generate resource Actor firstname:text lastname:text </p>
  <p> #3. rake db:migrate </p>
  <p> #4. controllers/actors_controller.rb --> def index | @glumci = Actor.all | end </p>
  <p> #5. routes.rb --> root 'actors#index'</p>
  <p> #6. Add create & destroy methods to controller | check GitHub commit |</p>
  <p> #7. Add Bootstrap CND links for styling and functionality</p>

</div>


</div>

app/views/actors/new.html.erb
<div class="container">

<h1> <img src="http://perfectial.com/wp-content/uploads/2015/02/ruby.png" style="height:32px; width:auto; float:left; padding-right: 10px;"> Absolute beginner's tutorial to Rails and AJAX </h1>
<hr />

<p>Add new Actor or Actress:</p>

<%= form_for @glumac do |actor| %>
  <%= actor.label :firstname %>
  <%= actor.text_field :firstname %>
  <br>
  <%= actor.label :lastname %>
  <%= actor.text_field :lastname %>
  <br>
  <%= actor.submit "Add", class:'btn btn-success'%>
<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RussQuickAjax</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- ### ### ### jQuery library ### ### ### -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

<!-- ### ### ### Bootstrap 3 ### ### ### -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap-theme.css">
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/npm.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.js"></script>

</head>
<body>

<%= yield %>

<div id="separator100" style="height:100px;">&nbsp;</div>
<footer style="padding:20px;">
  <p><img src="https://assets-cdn.github.com/images/modules/logos_page/Octocat.png" style="height:72px; width:auto;"></p>
</footer>
</body>

</html>